### PR TITLE
[Constants.js] Adding PHI (golden ratio) constant

### PR DESCRIPTION
**Pull request by gabrielPeart**
Adding new PHI constant: golden ratio (phi) : (1 + Math.sqrt(5)) / 2

### CODE REVIEW

**Comment by brenapp** [comment]
Shouldn't you define PHI as `(1 + Math.sqrt(5)) / 2`, as opposed to giving the actual decimal value, in the case of an implementation with a more precise numerical system. Chrome 48 will output 1 more decimal than you, ;)

**Comment by gabrielPeart** [comment]
@MayorMonty You are right, since the other constants were defined that way. I really appreciate ;)

**Comment by GGAlanSmithee** [comment]
If you want deterministic physics, the value should be the same for all platforms. Math ops should produce the same result, but browser implementations are notoriously different in the most wierd ways,

**Comment by gabrielPeart** [comment]
@GGAlanSmithee That was my initial thought, to be sure to have the same value no matter which browser is consuming it. 
But @MayorMonty added a valid point, since the other constants aren't following this logic.
I edited my initial code for the sake of consistency, but it is a very interesting discussion. Thank you guys!

**Pull request closed without merging**
